cbr.api.url=http://www.cbr.ru/scripts/XML_daily.asp
cbr.api.date_format=dd/MM/yyyy
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.root=DEBUG
logging.level.org.springframework=INFO
logging.level.com.tbank=DEBUG
logging.file.name=application.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.logstash.enabled=true
logging.logstash.host=localhost
logging.logstash.port=5044
management.endpoints.web.exposure.include=*